name: publish storybook
on:
  push:
    branches:
      - master
jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@main
        with:
          node-version: 12.x
      - name: get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: Publish storybook on github pages
        run: yarn deploy-storybook --ci
