name: publish storybook
on:
  push:
    branches:
      - master
env:
  GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
jobs:
  my_first_job:
    steps:
      - name: Publish storybook on github pages
        run: yarn deploy-storybook --ci
